// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sdk/plugin.proto

package sdk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_sdk_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_proto_rawDescGZIP(), []int{0}
}

type GetMetadataResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version            string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	SupportedResources []string               `protobuf:"bytes,3,rep,name=supported_resources,json=supportedResources,proto3" json:"supported_resources,omitempty"`
	Capabilities       map[string]string      `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_sdk_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *GetMetadataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMetadataResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetMetadataResponse) GetSupportedResources() []string {
	if x != nil {
		return x.SupportedResources
	}
	return nil
}

func (x *GetMetadataResponse) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Input         []byte                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Parameters    map[string][]byte      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Credentials   map[string]string      `protobuf:"bytes,4,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Context       map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_sdk_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ExecuteRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExecuteRequest) GetParameters() map[string][]byte {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ExecuteRequest) GetCredentials() map[string]string {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ExecuteRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_sdk_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_sdk_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_proto_rawDescGZIP(), []int{4}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_sdk_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_sdk_plugin_proto protoreflect.FileDescriptor

const file_sdk_plugin_proto_rawDesc = "" +
	"\n" +
	"\x10sdk/plugin.proto\x12\x12maschine.plugin.v1\"\x14\n" +
	"\x12GetMetadataRequest\"\x94\x02\n" +
	"\x13GetMetadataResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12/\n" +
	"\x13supported_resources\x18\x03 \x03(\tR\x12supportedResources\x12]\n" +
	"\fcapabilities\x18\x04 \x03(\v29.maschine.plugin.v1.GetMetadataResponse.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x03\n" +
	"\x0eExecuteRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x14\n" +
	"\x05input\x18\x02 \x01(\fR\x05input\x12R\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v22.maschine.plugin.v1.ExecuteRequest.ParametersEntryR\n" +
	"parameters\x12U\n" +
	"\vcredentials\x18\x04 \x03(\v23.maschine.plugin.v1.ExecuteRequest.CredentialsEntryR\vcredentials\x12I\n" +
	"\acontext\x18\x05 \x03(\v2/.maschine.plugin.v1.ExecuteRequest.ContextEntryR\acontext\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a>\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12M\n" +
	"\bmetadata\x18\x03 \x03(\v21.maschine.plugin.v1.ExecuteResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x14\n" +
	"\x12HealthCheckRequest\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9c\x02\n" +
	"\x06Plugin\x12^\n" +
	"\vGetMetadata\x12&.maschine.plugin.v1.GetMetadataRequest\x1a'.maschine.plugin.v1.GetMetadataResponse\x12R\n" +
	"\aExecute\x12\".maschine.plugin.v1.ExecuteRequest\x1a#.maschine.plugin.v1.ExecuteResponse\x12^\n" +
	"\vHealthCheck\x12&.maschine.plugin.v1.HealthCheckRequest\x1a'.maschine.plugin.v1.HealthCheckResponseB Z\x1emaschine.io/plugin-sdk/sdk;sdkb\x06proto3"

var (
	file_sdk_plugin_proto_rawDescOnce sync.Once
	file_sdk_plugin_proto_rawDescData []byte
)

func file_sdk_plugin_proto_rawDescGZIP() []byte {
	file_sdk_plugin_proto_rawDescOnce.Do(func() {
		file_sdk_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_plugin_proto_rawDesc), len(file_sdk_plugin_proto_rawDesc)))
	})
	return file_sdk_plugin_proto_rawDescData
}

var file_sdk_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_sdk_plugin_proto_goTypes = []any{
	(*GetMetadataRequest)(nil),  // 0: maschine.plugin.v1.GetMetadataRequest
	(*GetMetadataResponse)(nil), // 1: maschine.plugin.v1.GetMetadataResponse
	(*ExecuteRequest)(nil),      // 2: maschine.plugin.v1.ExecuteRequest
	(*ExecuteResponse)(nil),     // 3: maschine.plugin.v1.ExecuteResponse
	(*HealthCheckRequest)(nil),  // 4: maschine.plugin.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 5: maschine.plugin.v1.HealthCheckResponse
	nil,                         // 6: maschine.plugin.v1.GetMetadataResponse.CapabilitiesEntry
	nil,                         // 7: maschine.plugin.v1.ExecuteRequest.ParametersEntry
	nil,                         // 8: maschine.plugin.v1.ExecuteRequest.CredentialsEntry
	nil,                         // 9: maschine.plugin.v1.ExecuteRequest.ContextEntry
	nil,                         // 10: maschine.plugin.v1.ExecuteResponse.MetadataEntry
}
var file_sdk_plugin_proto_depIdxs = []int32{
	6,  // 0: maschine.plugin.v1.GetMetadataResponse.capabilities:type_name -> maschine.plugin.v1.GetMetadataResponse.CapabilitiesEntry
	7,  // 1: maschine.plugin.v1.ExecuteRequest.parameters:type_name -> maschine.plugin.v1.ExecuteRequest.ParametersEntry
	8,  // 2: maschine.plugin.v1.ExecuteRequest.credentials:type_name -> maschine.plugin.v1.ExecuteRequest.CredentialsEntry
	9,  // 3: maschine.plugin.v1.ExecuteRequest.context:type_name -> maschine.plugin.v1.ExecuteRequest.ContextEntry
	10, // 4: maschine.plugin.v1.ExecuteResponse.metadata:type_name -> maschine.plugin.v1.ExecuteResponse.MetadataEntry
	0,  // 5: maschine.plugin.v1.Plugin.GetMetadata:input_type -> maschine.plugin.v1.GetMetadataRequest
	2,  // 6: maschine.plugin.v1.Plugin.Execute:input_type -> maschine.plugin.v1.ExecuteRequest
	4,  // 7: maschine.plugin.v1.Plugin.HealthCheck:input_type -> maschine.plugin.v1.HealthCheckRequest
	1,  // 8: maschine.plugin.v1.Plugin.GetMetadata:output_type -> maschine.plugin.v1.GetMetadataResponse
	3,  // 9: maschine.plugin.v1.Plugin.Execute:output_type -> maschine.plugin.v1.ExecuteResponse
	5,  // 10: maschine.plugin.v1.Plugin.HealthCheck:output_type -> maschine.plugin.v1.HealthCheckResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_sdk_plugin_proto_init() }
func file_sdk_plugin_proto_init() {
	if File_sdk_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_plugin_proto_rawDesc), len(file_sdk_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_plugin_proto_goTypes,
		DependencyIndexes: file_sdk_plugin_proto_depIdxs,
		MessageInfos:      file_sdk_plugin_proto_msgTypes,
	}.Build()
	File_sdk_plugin_proto = out.File
	file_sdk_plugin_proto_goTypes = nil
	file_sdk_plugin_proto_depIdxs = nil
}
